### ISSUE TITLE
-c regtest - came up error

### ISSUE THREAD

**Issue by madtomic** [sebastianst/GenesisZ#10]
Traceback (most recent call last):
  File "./genesis.py", line 231, in <module>
    main()
  File "./genesis.py", line 38, in main
    solution, nonce = loop.run_until_complete(findValidSolution(eh, args.solver))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "./genesis.py", line 190, in findValidSolution
    nonce, sols = await parseSolutions(solver)
  File "./genesis.py", line 220, in parseSolutions
    (sol_size, line)
AssertionError: Solver returned unexpected solution of size != 36:

Do you have any idea why this might happen? mainnet and testnet don't have this error. Please help!

**Comment by sebastianst** [comment]
silentarmy can only mine for parameters `N,K=200,9`. I'm currently trying to get tromp's solver to work for regtest so we can finally mine regtest solutions. Until then, `-c regtest` doesn't work.

**Comment by sebastianst** [comment]
closing in favour of #7 .

**Comment by sebastianst** [comment]
Tromp now supported, see end of #7
