### ISSUE TITLE
Doubt about -s

### ISSUE THREAD

**Issue by thedecentralized** [sebastianst/GenesisZ#17]
Hello, how is everything? hope so

In the line -s '/path/ to /equihash/equi' I have to put what specifically? can be any mass

**Comment by thedecentralized** [comment]
I managed to do it but now it shows this error = /

Chain: mainnet
Time: 1632280404
Start Nonce: 0000000000000000000000000000000000000000000000000000000000000000
Pubkey: 04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f
Solver: ['../equihash/equi']
Solver type: tromp
timestamp after substitution: The Economist 2016-10-29 Known unknown: Another crypto-currency is born. BTC#436254 0000000000000000044f321997f336d2908cf8c8d6893e88dbf067e2d949487d ETH#2521903 483039a6b6bd8bd05f0584f9a078d075e454925eb71c1f13eaff59b405a721bb DJIA close on 27 Oct 2016: 18,169.68
pszTimestamp: Zcash0b9c4eef8b7cc417ee5001e3500984b6fea35683a7cac141a043c42064835d34
TX/merkle root hash: c4eaa58879081de3c24a7b117ed2b28300e7ec4c4c1dff1d3f1268b7857a4ddb
Starting solver with command ['../equihash/equi', '-s', '-c', '-n', '0', '-r', '1', '-t', '1', '-x', '040000000000000000000000000000000000000000000000000000000000000000000000db4d7a85b768123f1dff1d4c4cece70083b2d27e117b4ac2e31d087988a5eac40000000000000000000000000000000000000000000000000000000000000000549f4a61ffff071f0000000000000000000000000000000000000000000000000000000000000000']
Solver started.
Banner:
WARNING: use of atomics hurts single threaded performance!
Looking for wagner-tree on ZcashPoW("0x...",0) with 10 20-bit digits and 1 threads
Using 2^10 buckets, 145MB of memory, and 1-way blake2b
Solver returned 3 solutions for nonce 0000000000000000000000000000000000000000000000000000000000000000
Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 42716 is closed
Traceback (most recent call last):
  File "/home/user/Desktop/zcash/GenesisZ/solvers.py", line 54, in run
    nonce, sols = await self.parse_solutions()
  File "/home/user/Desktop/zcash/GenesisZ/solvers.py", line 146, in parse_solutions
    raise SolverException('Solver stopped before valid solution found.')
solvers.SolverException: Solver stopped before valid solution found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./genesis.py", line 184, in <module>
    main()
  File "./genesis.py", line 45, in main
    solution, nonce = loop.run_until_complete(solver.run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/Desktop/zcash/GenesisZ/solvers.py", line 61, in run
    self.solver.terminate()
  File "/usr/lib/python3.8/asyncio/subprocess.py", line 141, in terminate
    self._transport.terminate()
  File "/usr/lib/python3.8/asyncio/base_subprocess.py", line 150, in terminate
    self._proc.terminate()
  File "/usr/lib/python3.8/subprocess.py", line 1938, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python3.8/subprocess.py", line 1933, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process

**Comment by crypticcoin-renewed** [comment]
run it with "-r 10000" appended at the end. That fixed it for me
